- name: Install dependencies
  apt:
      state: present
      update_cache: yes
      name: "{{ item }}"
  with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add docker repo key
  apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

- name: Add docker repository
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present

- name: install docker
  apt:
      name: docker-ce
      update_cache: yes

- name: install docker compose binary
  get_url:
      url: "https://github.com/docker/compose/releases/download/1.17.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
      dest: "/usr/local/bin/docker-compose"
      mode: 0755
      force: yes
